# Generated by Django 3.0.3 on 2020-03-27 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_another_author'),
        ('posts', '0004_auto_20200327_0854'),
    ]

    operations = [
    ]
