# Generated by Django 3.0.3 on 2020-03-27 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_merge_20200327_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='another_author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='origin_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_type',
        ),
    ]
