# Generated by Django 3.0.3 on 2020-03-26 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_foaf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FOAF',
        ),
    ]
