# Generated by Django 3.0.3 on 2020-03-27 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20200327_0647'),
        ('friends', '0003_delete_foaf'),
    ]

    operations = [
    ]
